name: Build and run image tests for all architectures
on:
  # We cannot trigger just on PRs as these do not have write permissions to GHCR from forks.
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  # Instead we use the label to gate running this.
  pull_request_target:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
    pr-check-label:
      if: contains(github.event.pull_request.labels.*.name, 'ok-container-test')
      name: PR - prevent run without label
      runs-on: ubuntu-latest
      environment: pr
      steps:
        - run: echo "Proceed"

    pr-image-tests-build-images:
      name: PR - build images
      # DO NOT MERGE - revert to main, which will fail
      uses: fluent/fluent-bit/.github/workflows/call-build-images.yaml@default_multiarch_containers_2
      needs: pr-check-label
      with:
        version: ${{ github.event.pull_request.head.ref }}
        registry: ghcr.io
        username: ${{ github.actor }}
        image: ${{ github.repository }}/pr-${{ github.event.number }}
        environment: pr
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}

    pr-image-tests-smoke-test-images:
      name: PR - smoke test images
      needs: [pr-check-label, pr-image-tests-build-images]
      # DO NOT MERGE - revert to main, which will fail
      uses: fluent/fluent-bit/.github/workflows/call-test-images.yaml@default_multiarch_containers_2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        image: ${{ github.repository }}/pr-${{ github.event.number }}
        image-tag: ${{ github.event.pull_request.head.ref }}
        environment: pr
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}

    pr-image-tests-classic-docker-build:
      name: PR - Classic docker build test
      needs: pr-check-label
      runs-on: ubuntu-latest
      environment: pr
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the classic build test image
        # We only want to confirm it builds with classic mode, nothing else
        run: |
          docker build --target production -f ./dockerfiles/Dockerfile .
        env:
          # Ensure we disable buildkit
          DOCKER_BUILDKIT: 0
        shell: bash

    pr-image-tests-post-label:
      name: PR - image tests complete
      runs-on: ubuntu-latest
      needs:
        - pr-image-tests-smoke-test-images
        - pr-image-tests-classic-docker-build
      steps:
        - uses: actions-ecosystem/action-add-labels@v1
          name: Label the PR
          with:
            labels: ci/container-test-ok
            github_token: ${{ secrets.GITHUB_TOKEN }}
            number: ${{ github.event.pull_request.number }}
            repo: fluent/fluent-bit
